### ISSUE TITLE
Link of paper seems to be broken.

### ISSUE THREAD

**Issue by izuna385** [henryrosalesmendez/EL_exp#1]
Thanks for uploading codes. I can't wait reading your paper.
It seems that link of paper seems to be broken(or, paper has not been uploaded to links.)

Is there any plan to upload accepted paper, or would you know when to upload that?
If you'd know, I'd appreciate it.

Thanks.

**Comment by henryrosalesmendez** [comment]
Thank you for being interested in my work! The link is working now, I was waiting to have the camera-ready version.

Cheers!
Henry
